from distutils.core import setup

setup(
    name='appacitive-python-sdk',
    version='',
    packages=['pysdk.lib.python2.7.distutils', 'pysdk.lib.python2.7.encodings', 'pysdk.lib.python2.7.site-packages.pip',
              'pysdk.lib.python2.7.site-packages.pip.vcs', 'pysdk.lib.python2.7.site-packages.pip.vendor',
              'pysdk.lib.python2.7.site-packages.pip.vendor.distlib',
              'pysdk.lib.python2.7.site-packages.pip.vendor.distlib._backport',
              'pysdk.lib.python2.7.site-packages.pip.vendor.html5lib',
              'pysdk.lib.python2.7.site-packages.pip.vendor.html5lib.trie',
              'pysdk.lib.python2.7.site-packages.pip.vendor.html5lib.filters',
              'pysdk.lib.python2.7.site-packages.pip.vendor.html5lib.serializer',
              'pysdk.lib.python2.7.site-packages.pip.vendor.html5lib.treewalkers',
              'pysdk.lib.python2.7.site-packages.pip.vendor.html5lib.treebuilders',
              'pysdk.lib.python2.7.site-packages.pip.commands', 'pysdk.lib.python2.7.site-packages.pip.backwardcompat',
              'pysdk.lib.python2.7.site-packages._markerlib', 'pysdk.lib.python2.7.site-packages.setuptools',
              'pysdk.lib.python2.7.site-packages.setuptools.tests',
              'pysdk.lib.python2.7.site-packages.setuptools.command',
              'pysdk.lib.python2.7.site-packages.setuptools._backport',
              'pysdk.lib.python2.7.site-packages.setuptools._backport.hashlib', 'pysdk.local.lib.python2.7.distutils',
              'pysdk.local.lib.python2.7.encodings', 'pysdk.local.lib.python2.7.site-packages.pip',
              'pysdk.local.lib.python2.7.site-packages.pip.vcs', 'pysdk.local.lib.python2.7.site-packages.pip.vendor',
              'pysdk.local.lib.python2.7.site-packages.pip.vendor.distlib',
              'pysdk.local.lib.python2.7.site-packages.pip.vendor.distlib._backport',
              'pysdk.local.lib.python2.7.site-packages.pip.vendor.html5lib',
              'pysdk.local.lib.python2.7.site-packages.pip.vendor.html5lib.trie',
              'pysdk.local.lib.python2.7.site-packages.pip.vendor.html5lib.filters',
              'pysdk.local.lib.python2.7.site-packages.pip.vendor.html5lib.serializer',
              'pysdk.local.lib.python2.7.site-packages.pip.vendor.html5lib.treewalkers',
              'pysdk.local.lib.python2.7.site-packages.pip.vendor.html5lib.treebuilders',
              'pysdk.local.lib.python2.7.site-packages.pip.commands',
              'pysdk.local.lib.python2.7.site-packages.pip.backwardcompat',
              'pysdk.local.lib.python2.7.site-packages._markerlib',
              'pysdk.local.lib.python2.7.site-packages.setuptools',
              'pysdk.local.lib.python2.7.site-packages.setuptools.tests',
              'pysdk.local.lib.python2.7.site-packages.setuptools.command',
              'pysdk.local.lib.python2.7.site-packages.setuptools._backport',
              'pysdk.local.lib.python2.7.site-packages.setuptools._backport.hashlib', 'PyAppacitive',
              'PyAppacitive.src', 'PyAppacitive.src.cloudcode', 'PyAppacitive.src.utilities', 'PyAppacitive.tests'],
    url='',
    license='',
    author='sathley',
    author_email='',
    description=''
)
